clothes = {
	--
	["Hats"] = {
		
	{ name = "Red Bandana", texture = "bandred", model = "bandana", id = 16, price = 150},
	{ name = "Blue Bandana",texture = "bandblue", model = "bandana", id = 16, price = 150},
	{ name = "Green Bandana",texture = "bandgang", model = "bandana", id = 16, price = 150},
	{ name = "Black Bandana",texture = "bandblack", model = "bandana",id =  16, price = 150},
	{ name = "Red Bandana Front",texture = "bandred2", model = "bandknots", id = 16, price = 150},
	{ name = "Blue Bandana Front",texture = "bandblue2", model = "bandknots", id = 16, price = 150},
	{ name = "Green Bandana Front",texture = "bandgang2", model = "bandknots", id = 16, price = 150},
	{ name = "Black Bandana Front",texture = "bandblack2", model = "bandknots", id = 16, price = 150},
	{ name = "Green Knit Cap",texture = "capknitgrn", model = "capknit", id = 16, price = 150},
	{ name = "Trucker Cap",texture = "captruck", model = "captruck", id = 16, price = 150},
	{ name = "Cowboy Hat 1",texture = "cowboy", model = "cowboy", id = 16, price = 150},
	{ name = "Cowboy Hat 2",texture = "hattiger", model = "cowboy", id = 16, price = 150},
	{ name = "Red Motorbike Helmet",texture = "helmet", model = "helmet", id = 16, price = 150},
	{ name = "Blue Motorbike Helmet",texture = "moto", model = "moto", id = 16, price = 150},
	{ name = "Boxing Cap",texture = "boxingcap", model = "boxingcap", id = 16, price = 150},
	{ name = "Hockey Mask",texture = "hockey", model = "hockeymask", id = 16, price = 150},
	{ name = "Green Cap Front",texture = "capgang", model = "cap", id = 16, price = 150},
	{ name = "Green Cap Back",texture = "capgangback", model = "capback", id = 16, price = 150},
	{ name = "Green Cap Side",texture = "capgangside", model = "capside", id = 16, price = 150},
	{ name = "Green Cap Back 2",texture = "capgangover", model = "capovereye", id = 16, price = 150},
	{ name = "Green Cap Up",texture = "capgangup", model = "caprimup", id = 16, price = 150},
	{ name = "Biker Helmet",texture = "bikerhelmet", model = "bikerhelmet", id = 16, price = 150},
	{ name = "Red Cap Front",texture = "capred", model = "cap", id = 16, price = 150},
	{ name = "Red Cap Back",texture = "capredback", model = "capback", id = 16, price = 150},
	{ name = "Red Cap Side",texture = "capredside", model = "capside", id = 16, price = 150},
	{ name = "Red Cap Back 2",texture = "capredover", model = "capovereye", id = 16, price = 150},
	{ name = "Red Cap Up",texture = "capredup", model = "caprimup", id = 16, price = 150},
	{ name = "Blue Cap Front",texture = "capblue", model = "cap", id = 16, price = 150},
	{ name = "Blue Cap Back",texture = "capblueback", model = "capback", id = 16, price = 150},
	{ name = "Blue Cap Side",texture = "capblueside", model = "capside", id = 16, price = 150},
	{ name = "Blue Cap Back 2",texture = "capblueover", model = "capovereye", id = 16, price = 150},
	{ name = "Blue Cap Up",texture = "capblueup", model = "caprimup", id = 16, price = 150},
	{ name = "Black Beanie",texture = "skullyblk", model = "skullycap", id = 16, price = 150},
	{ name = "Green Beanie",texture = "skullygrn", model = "skullycap", id = 16, price = 150},
	{ name = "Black Sunhat",texture = "hatmanblk", model = "hatmanc", id = 16, price = 150},
	{ name = "Striped Sunhat",texture = "hatmancplaid", model = "hatmanc", id = 16, price = 150},
	{ name = "Yellow Cap Front",texture = "capzip", model = "cap", id = 16, price = 150},
	{ name = "Yellow Cap Back",texture = "capzipback", model = "capback", id = 16, price = 150},
	{ name = "Yellow Cap Side",texture = "capzipside", model = "capside", id = 16, price = 150},
	{ name = "Yellow Cap Back 2",texture = "capzipover", model = "capovereye", id = 16, price = 150},
	{ name = "Red Cap Up",texture = "capzipup", model = "caprimup", id = 16, price = 150},
	{ name = "Red Beret",texture = "beretred", model = "beret", id = 16, price = 150},
	{ name = "Black Beret",texture = "beretblk", model = "beret", id = 16, price = 150},
	{ name = "Black Beret",texture = "capblk", model = "cap", id = 16, price = 150},
	{ name = "Black Cap Back",texture = "capblkback", model = "capback", id = 16, price = 150},
	{ name = "Black Cap Side",texture = "capblkside", model = "capside", id = 16, price = 150},
	{ name = "Black Cap Back 2",texture = "capblkover", model = "capovereye", id = 16, price = 150},
	{ name = "Black Cap Up",texture = "capblkup", model = "caprimup", id = 16, price = 150},
	{ name = "Dark Detective  Hat",texture = "trilbydrk", model = "trilby", id = 16, price = 150},
	{ name = "Light Detective Hat",texture = "trilbylght", model = "trilby", id = 16, price = 150},
	{ name = "Black Bowler",texture = "bowler", model = "bowler", id = 16, price = 150},
	{ name = "Red Bowler",texture = "bowlerred", model = "bowler", id = 16, price = 150},
	{ name = "Blue Bowler",texture = "bowlerblue", model = "bowler", id = 16, price = 150},
	{ name = "Yellow Bowler",texture = "bowleryellow", model = "bowler", id = 16, price = 150},
	{ name = "Boater Hat 1",texture = "boater", model = "boater", id = 16, price = 150},
	{ name = "Green Bowler",texture = "bowlergang", model = "bowler", id = 16, price = 150},
	{ name = "Boater Hat 2",texture = "boaterblk", model = "boater", id = 16, price = 150},
	},
	--Shirts
	["Shirts"] = {

	{ name = "No Shirt",texture = "player_torso", model = "torso", id = 0, price = 50},
	{ name = "Black Tanktop",texture = "vestblack", model = "vest", id = 0, price = 250},
	{ name = "White Tanktop",texture = "vest", model = "vest", id = 0, price = 250},
	{ name = "Striped T-Shirt",texture = "tshirt2horiz", model = "tshirt2", id = 0, price = 250},
	{ name = "White T-Shirt",texture = "tshirtwhite", model = "tshirt", id = 0, price = 250},
	{ name = "I <3 LS T-Shirt",texture = "tshirtilovels", model = "tshirt",id = 0, price = 250},
	{ name = "Homies T-Shirt",texture = "tshirtblunts", model = "tshirt", id = 0, price = 250},
	{ name = "Red Checkered Shirt",texture = "shirtbplaid", model = "shirtb", id = 0, price = 250},
	{ name = "Blue Checkered Shirt",texture = "shirtbcheck", model = "shirtb", id = 0, price = 250},
	{ name = "Shirt & T-Shirt Combination",texture = "field", model = "field", id = 0, price = 250},
	{ name = "Green T-Shirt",texture = "tshirterisyell", model = "tshirt", id = 0, price = 250},
	{ name = "Orange T-Shirt",texture = "tshirterisorn", model = "tshirt", id=0, price = 250},
	{ name = "Blue/Red Tracktop",texture = "trackytop2eris", model = "trackytop1", id = 0, price = 250},
	{ name = "Red/White Jacket",texture = "bbjackrim", model = "bbjack", id = 0, price = 250},
	{ name = "Rockstar Jacket",texture = "bballjackrstar", model = "bbjack", id = 0, price = 250},
	{ name = "Basketball Jersey 1",texture = "baskballdrib", model = "baskball", id = 0, price = 250},
	{ name = "Basketball Jersey 2",texture = "baskballrim", model = "baskball", id = 0, price = 250},
	{ name = "69er's Jersey",texture = "sixtyniners", model = "tshirt", id = 0, price = 250},
	{ name = "Bandits Baseball Jersey",texture = "bandits", model = "baseball", id = 0, price = 250},
	{ name = "Red ProLaps T-Shirt",texture = "tshirtprored", model = "tshirt", id = 0, price = 250},
	{ name = "Black ProLaps T-Shirt",texture = "tshirtproblk", model = "tshirt", id = 0, price = 250},
	{ name = "ProLaps Tracktop",texture = "trackytop1pro", model = "trackytop1", id = 0, price = 250},
	{ name = "Hockey Jersey",texture = "hockeytop", model = "sweat", id = 0, price = 250},
	{ name = "ProLaps White Sleeve",texture = "bbjersey", model = "sleevt", id = 0, price = 250},
	{ name = "Shellsuit Tracktop",texture = "shellsuit", model = "trackytop1", id = 0, price = 250},
	{ name = "White TruReligion Shirt",texture = "tshirtheatwht", model = "tshirt", id = 0, price = 250},
	{ name = "Bobo Monkey T-Shirt", texture = "tshirtbobomonk", model = "tshirt", id = 0, price = 250},
	{ name = "#80 Red T-Shirt", texture = "tshirtbobored", model = "tshirt", id = 0, price = 250},
	{ name = "Base-5 T-Shirt", texture = "tshirtbase5", model = "tshirt", id = 0, price = 250},
	{ name = "SubUrban T-Shirt", texture = "tshirtsuburb", model = "tshirt", id = 0, price = 250},
	{ name = "QuickSilver Hoodie", texture = "hoodyamerc", model = "hoodya", id = 0, price = 250},
	{ name = "Base-5 Hoody", texture = "hoodyabase5", model = "hoodya", id = 0, price = 250},
	{ name = "Rockstar Hoody", texture = "hoodyarockstar", model = "hoodya", id = 0, price = 250},
	{ name = "White/Blue T-Shirt Coat", texture = "wcoatblue", model = "wcoat", id = 0, price = 250},
	{ name = "Military Green Shirt", texture = "coach", model = "coach", id = 0, price = 250},
	{ name = "Semi Military Green Shirt", texture = "semicoach", model = "coach", id = 0, price = 250},
	{ name = "Rockstar Sweater", texture = "sweatrstar", model = "sweat", id = 0, price = 250},
	{ name = "Blue Rockstar Hoody", texture = "hoodyAblue", model = "hoodyA", id = 0, price = 250},
	{ name = "Black Rockstar Hoody", texture = "hoodyAblack", model = "hoodyA", id = 0, price = 250},
	{ name = "Green Rockstar Hoody", texture = "hoodyAgreen", model = "hoodyA", id = 0, price = 250},
	{ name = "Brown Sleeve Shirt", texture = "sleevtbrown", model = "sleevt", id = 0, price = 250},
	{ name = "Light Blue Shirt", texture = "shirtablue", model = "shirta", id = 0, price = 250},
	{ name = "Light Yellow Shirt", texture = "shirtayellow", model = "shirta", id = 0, price = 250},
	{ name = "Grey Shirt", texture = "shirtagrey", model = "shirta", id = 0, price = 250},
	{ name = "Green Shirt", texture = "shirtbgang", model = "shirtb", id = 0, price = 250},
	{ name = "Cream ZIP T-Shirt", texture = "tshirtzipcrm", model = "tshirt", id = 0, price = 250},
	{ name = "Grey ZIP T-Shirt", texture = "tshirtzipgry", model = "tshirt", id = 0, price = 250},
	{ name = "Faded Demin Jacket", texture = "denimfade", model = "denimfade", id = 0, price = 250},
	{ name = "Bowling T-Shirt", texture = "bowling", model = "hawaii", id = 0, price = 250},
	{ name = "Beige Hoody Jacket", texture = "hoodjackbeige", model = "hoodjack", id = 0, price = 250},
	{ name = "Gold Basketball Jersey", texture = "baskballloc", model = "backball", id = 0, price = 250},
	{ name = "Handcuff's T-Shirt", texture = "tshirtlocgrey", model = "tshirt", id = 0, price = 250},
	{ name = "Grey Uzi T-Shirt", texture = "tshirtmaddgrey", model = "tshirt", id = 0, price = 250},
	{ name = "Green Uzi T-Shirt", texture = "tshirtmaddgrn", model = "tshirt", id = 0, price = 250},
	{ name = "Grey Suit Jacket", texture = "suit1grey", model = "suit1", id = 0, price = 250},
	{ name = "Black Suit Jacket", texture = "suit1blk", model = "suit1", id = 0, price = 250},
	{ name = "Leather Jacket", texture = "leather", model = "leather", id = 0, price = 250},
	{ name = "Painter Jacket", texture = "painter", model = "painter", id = 0, price = 250},
	{ name = "White Hawaii Shirt", texture = "hawaiiwht", model = "hawaii", id = 0, price = 250},
	{ name = "White Hawaii Shirt 2", texture = "hawaiired", model = "hawaii", id = 0, price = 250},
	{ name = "Sport's Tracktop", texture = "sportjack", model = "trackytop1", id = 0, price = 250},
	{ name = "Red Suit Jacket", texture = "suit1red", model = "suit1", id = 0, price = 250},
	{ name = "Blue Suit Jacket", texture = "suit1blue", model = "suit1", id = 0, price = 250},
	{ name = "Yellow Suit Jacket", texture = "suit1yellow", model = "suit1", id = 0, price = 250},
	{ name = "Green Tuxedo Jacket", texture = "suit2green", model = "suit2", id = 0, price = 250},
	{ name = "Black Tuxedo Jacket", texture = "tuxedo", model = "suit2", id = 0, price = 250},
	{ name = "Green Suit Jacket", texture = "suit1gang", model = "suit1", id = 0, price = 250},
	{ name = "Blue R Sleeve", texture = "letter", model = "sleevt", id = 0, price = 250},
	},
	--Trousers
	["Pants"] = {

	{ name = "No Trousers",texture = "player_legs", model = "legs", id = 2, price = 50},
	{ name = "Black Boxer Briefs",texture = "legsblack", model = "legs", id = 2, price = 750},
	{ name = "Hearted Boxer Briefs",texture = "legsheart", model = "legs", id = 2, price = 750},
	{ name = "Camo Green Trousers",texture = "worktrcamogrn", model = "worktr", id = 2, price = 750},
	{ name = "Camo Grey Trousers",texture = "worktrcamogry", model = "worktr", id = 2, price = 750},
	{ name = "Grey Cargopants",texture = "worktrgrey", model = "worktr", id = 2, price = 750},
	{ name = "Khaki Cargopants",texture = "worktrkhaki", model = "worktr", id = 2, price = 750},
	{ name = "White Trackpants",texture = "tracktr", model = "tracktr", id = 2, price = 750},
	{ name = "Navy Blue Trackpants",texture = "tracktreris", model = "tracktr", id = 2, price = 750},
	{ name = "Denim Jeans",texture = "jeansdenim", model = "jeans", id = 2, price = 750},
	{ name = "Biege Khakis",texture = "biegetr", model = "chinosb", id = 2, price = 750},
	{ name = "Red Trackpants",texture = "tracktrpro", model = "tracktr", id = 2, price = 750},
	{ name = "Grey Trackpants",texture = "tracktrwhstr", model = "tracktr", id = 2, price = 750},
	{ name = "Blue Trackpants",texture = "tracktrblue", model = "tracktr", id = 2, price = 750},
	{ name = "Green Trackpants",texture = "tracktrgang", model = "tracktr", id = 2, price = 750},
	{ name = "White Boxing Shorts",texture = "bbshortwht", model = "boxingshort",id =  2, price = 750},
	{ name = "Blood Red Boxing Shorts",texture = "bbshort", model = "boxingshort", id = 2, price = 750},
	{ name = "Regular Red Boxing Shorts",texture = "bbshortred", model = "boxingshort", id = 2, price = 750},
	{ name = "Muli-Color Trackpants",texture = "shellsuittr", model = "tracktr", id = 2, price = 750},
	{ name = "Grey Cargoshorts",texture = "shortsgrey", model = "shorts", id = 2, price = 750},
	{ name = "Khaki Cargoshorts",texture = "shortskhaki", model = "shorts", id = 2, price = 750},
	{ name = "Green Shorts 1",texture = "chongergang", model = "chonger", id = 2, price = 750},
	{ name = "Red Shorts",texture = "chongerred", model = "chonger", id = 2, price = 750},
	{ name = "Blue Shorts",texture = "chongerblue", model = "chonger", id = 2, price = 750},
	{ name = "Green Shorts 2",texture = "shortsgang", model = "shorts", id = 2, price = 750},
	{ name = "Denim Green Jeans",texture = "denimgang", model = "jeans", id = 2, price = 750},
	{ name = "Denim Red Jeans",texture = "denimred", model = "jeans", id = 2, price = 750},
	{ name = "Biege Chinos",texture = "chinosbiege", model = "chinosb", id = 2, price = 750},
	{ name = "Khaki Chinos",texture = "chinoskhaki", model = "chinosb", id = 2, price = 750},
	{ name = "Chino Shorts",texture = "cutoffchinos", model = "shorts", id = 2, price = 750},
	{ name = "Blue Chino Shorts",texture = "cutoffchinosblue", model = "shorts", id = 2, price = 750},
	{ name = "Black Chinos",texture = "chinosblack", model = "chinosb", id = 2, price = 750},
	{ name = "Blue Chinos",texture = "chinosblue", model = "chinosb", id = 2, price = 750},
	{ name = "Leather Jeans 1",texture = "leathertr", model = "leathertr", id = 2, price = 750},
	{ name = "Leather Jeans 2",texture = "leathertrchaps", model = "leathertr", id = 2, price = 750},
	{ name = "Grey Suit Pants",texture = "suit1trgrey", model = "suit1tr", id = 2, price = 750},
	{ name = "Black Suit Pants",texture = "suit1trblk", model = "suit1tr", id = 2, price = 750},
	{ name = "Demin Cut-Off Shorts",texture = "cutoffdemins", model = "shorts", id = 2, price = 750},
	{ name = "Red Suit Pants",texture = "suit1trred", model = "suit1tr", id = 2, price = 750},
	{ name = "Blue Suit Pants",texture = "suit1trblue", model = "suit1tr", id = 2, price = 750},
	{ name = "Gold Suit Pants",texture = "suit1tryellow", model = "suit1tr", id = 2, price = 750},
	{ name = "Green Tuxedo Pants",texture = "suit1trgreen", model = "suit1tr", id = 2, price = 750},
	{ name = "Black Tuxedo Pants",texture = "suit1trblk2", model = "suit1tr", id = 2, price = 750},
	{ name = "Green Suit Pants",texture = "suit1trgang", model = "suit1tr", id = 2, price = 750},
},
	--Shoes

["Shoes"] = {
	{ name = "No Shoes", texture = "foot", model = "feet", id = 3, price = 1050},
	{ name = "Cowboy Boots", texture = "cowboyboot2", model = "biker", id = 3, price = 1050},
	{ name = "White & Grey BasketBall Shoes", texture = "bask2semi", model = "bask1", id = 3, price = 1050},
	{ name = "White Basketball Shoes", texture = "bask1eris", model = "bask1", id = 3, price = 1050},
	{ name = "Green Sneakers", texture = "sneakerbincgang", model = "sneaker", id = 3, price = 1050},
	{ name = "Blue Sneakers", texture = "sneakerbincblue", model = "sneaker", id = 3, price = 1050},
	{ name = "Black Sneakers", texture = "sneakerbincblk", model = "sneaker", id = 3, price = 1050},
	{ name = "Black Sandals", texture = "sandal", model = "flipflop", id = 3, price = 1050},
	{ name = "Black Sandals w/th Socks", texture = "sandalsock", model = "flipflop", id = 3, price = 1050},
	{ name = "Black & Blue Flip-Flops", texture = "flipflop", model = "flipflop", id = 3, price = 1050},
	{ name = "White & Blue Hi-Tops", texture = "hitop", model = "bask1", id = 3, price = 1050},
	{ name = "Black Converse Shoes 1", texture = "convproblk", model = "conv", id = 3, price = 1050},
	{ name = "Blue Converse Shoes", texture = "convproblu", model = "conv", id = 3, price = 1050},
	{ name = "Green Converse Shoes", texture = "convprogrn", model = "conv", id = 3, price = 1050},
	{ name = "Red Sneakers", texture = "sneakerprored", model = "sneaker", id = 3, price = 1050},
	{ name = "Blue Sneakers", texture = "sneakerproblu", model = "sneaker", id = 3, price = 1050},
	{ name = "White Sneakers 1", texture = "sneakerprowht", model = "sneaker", id = 3, price = 1050},
	{ name = "White & Red Basketball Shoes", texture = "bask1prowht", model = "bask1", id = 3, price = 1050},
	{ name = "Black Basketball Shoes", texture = "bask1problk", model = "bask1", id = 3, price = 1050},
	{ name = "Boxing Shoes", texture = "boxingshoe", model = "biker", id = 3, price = 1050},
	{ name = "Black Converse Shoes 2", texture = "convheatblk", model = "conv", id = 3, price = 1050},
	{ name = "Red Converse Shoes", texture = "convheatred", model = "conv", id = 3, price = 1050},
	{ name = "Orange Converse Shoes", texture = "convheatorn", model = "conv", id = 3, price = 1050},
	{ name = "White Sneakers", texture = "sneakerheatwht", model = "sneaker", id = 3, price = 1050},
	{ name = "Grey Sneakers", texture = "sneakerheatgry", model = "sneaker", id = 3, price = 1050},
	{ name = "Black & Grey Sneakers", texture = "sneakerheatblk", model = "sneaker", id = 3, price = 1050},
	{ name = "White Sneakers 2", texture = "bask2heatwht", model = "bask1", id = 3, price = 1050},
	{ name = "Blue & White Basketball Shoes", texture = "bask2heatband", model = "bask1", id = 3, price = 1050},
	{ name = "Grey Basketball Shoes", texture = "timbergrey", model = "bask1", id = 3, price = 1050},
	{ name = "Red Basketball Shoes", texture = "timberred", model = "bask1", id = 3, price = 1050},
	{ name = "Brown Hiking Shoes", texture = "timberfawn", model = "bask1", id = 3, price = 1050},
	{ name = "Green Hiking Shoes", texture = "timberhike", model = "bask1", id = 3, price = 1050},
	{ name = "Black & White Cowboy Boots", texture = "cowboyboot", model = "biker", id = 3, price = 1050},
	{ name = "Biker Boots", texture = "biker", model = "biker", id = 3, price = 1050},
	{ name = "Snake Boots", texture = "snakeskin", model = "biker", id = 3, price = 1050},
	{ name = "Black Dress Shoes", texture = "shoedressblk", model = "shoe", id = 3, price = 1050},
	{ name = "Brown Dress Shoes", texture = "shoedressbrn", model = "shoe", id = 3, price = 1050},
	{ name = "Black & White Shoes", texture = "shoespaz", model = "shoe", id = 3, price = 1050},
	},
	--Hair
	["Hair"] = {
	{ name = "Regular Hair", texture = "player_face", model = "head", id = 1, price = 150},
	{ name = "Blond Hair", texture = "hairblond", model = "head", id = 1, price = 150},
	{ name = "Red Hair", texture = "hairred", model = "head", id = 1, price = 150},
	{ name = "Blue Hair", texture = "hairblue", model = "head", id = 1, price = 150},
	{ name = "Green Hair", texture = "hairgreen", model = "head", id = 1, price = 150},
	{ name = "Pink Hair", texture = "hairpink", model = "head", id = 1, price = 150},
	{ name = "Bald", texture = "bald", model = "head", id = 1, price = 150},
	{ name = "Bald w/th Beard", texture = "baldbeard", model = "head", id = 1, price = 150},
	{ name = "Bald w/th Stash", texture = "baldtash", model = "head", id = 1, price = 150},
	{ name = "Bald w/th Goatee", texture = "baldgoatee", model = "head", id = 1, price = 150},
	{ name = "High Fade", texture = "highfade", model = "head", id = 1, price = 150},
	{ name = "High Afro", texture = "highafro", model = "highafro", id = 1, price = 150},
	{ name = "Wedge", texture = "wedge", model = "wedge", id = 1, price = 150},
	{ name = "Slope", texture = "slope", model = "slope", id = 1, price = 150},
	{ name = "Curls", texture = "jhericurl", model = "jheri", id = 1, price = 150},
	{ name = "Cornrows", texture = "cornrows", model = "cornrows", id = 1, price = 150},
	{ name = "Blondrows", texture = "cornrowsb", model = "cornrows", id = 1, price = 150},
	{ name = "Tramline", texture = "tramline", model = "tramline", id = 1, price = 150},
	{ name = "Groove Cut", texture = "groovecut", model = "groovecut", id = 1, price = 150},
	{ name = "Mohawk", texture = "mohawk", model = "mohawk", id = 1, price = 150},
	{ name = "Blond Mohawk", texture = "mohawkblond", model = "mohawk", id = 1, price = 150},
	{ name = "Pink Mohawk", texture = "mohawkpink", model = "mohawk", id = 1, price = 150},
	{ name = "Mohawk w/th Beard", texture = "mohawkbeard", model = "mohawk", id = 1, price = 150},
	{ name = "Afro", texture = "afro", model = "afro", id = 1, price = 150},
	{ name = "Afro w/th Stash", texture = "afrotash", model = "afro", id = 1, price = 150},
	{ name = "Afro w/th Goatee", texture = "afrobeard", model = "afro", id = 1, price = 150},
	{ name = "Blond Afro", texture = "afroblond", model = "afro", id = 1, price = 150},
	{ name = "Flat Top", texture = "flattop", model = "flattop", id = 1, price = 150},
	{ name = "Elvis Hair", texture = "elvishair", model = "elvishair", id = 1, price = 150},
	{ name = "Regular w/th Beard", texture = "beard", model = "head", id = 1, price = 150},
	{ name = "Regular w/th Stash", texture = "tash", model = "head", id = 1, price = 150},
	{ name = "Regular w/th Goatee", texture = "goatee", model = "head", id = 1, price = 150},
	{ name = "Afro w/th Goatee", texture = "afrogoatee", model = "afro", id = 1, price = 150},
	
	},--Extras
	--[[["Extras"] = {
	{ name = "Gimpsuit", texture = "gimpleg", model = "gimpleg", id = 17, price = 2500},
	{ name = "Valet", texture = "valet", model = "valet", id = 17, price = 2500},
	{ name = "Croupier", texture = "croupier", model = "valet", id = 17, price = 2500},
	{ name = "Country", texture = "countrytr", model = "countrytr", id = 17, price = 2500},
	{ name = "Police", texture = "policetr", model = "policetr", id = 17, price = 2500},
	{ name = "Balaclava", texture = "balaclava", model = "balaclava", id = 17, price = 2500},
	{ name = "Pimpsuit", texture = "pimptr", model = "pimptr", id = 17, price = 2500},
	{ name = "Mech/Racer", texture = "garageleg", model = "garagetr", id = 17, price = 2500},
	{ name = "Medic", texture = "medictr", model = "medictr", id = 17, price = 2500},
	
	},]]--Glasses
	["Glasses"] = 
	{
	{ name = "Fake Nose", texture = "groucho", model = "groucho", id = 15, price = 1000},
	{ name = "Zorro", texture = "zorro", model = "zorromask", id = 15, price = 1000},
	{ name = "Eyepatch", texture = "eyepatch", model = "eyepatch", id = 15, price = 1000},
	{ name = "Glasses 1", texture = "glasses01", model = "glasses01", id = 15, price = 1000},
	{ name = "Glasses 4", texture = "glasses01", model = "glasses04", id = 15, price = 1000},
	{ name = "Red Band Mask", texture = "bandred3", model = "bandmask", id = 15, price = 1000},
	{ name = "Blue Band Mask", texture = "bandblue3", model = "bandmask", id = 15, price = 1000},
	{ name = "Green Band Mask", texture = "bandgang3", model = "bandmask", id = 15, price = 1000},
	{ name = "Black Band Mask", texture = "bandblack3", model = "bandmask", id = 15, price = 1000},
	{ name = "Glasses 1 Dark", texture = "glasses01dark", model = "glasses01", id = 15, price = 1000},
	{ name = "Glasses 4 Dark", texture = "glasses04dark", model = "glasses04", id = 15, price = 1000},
	{ name = "Glasses 3", texture = "glasses03", model = "glasses03", id = 15, price = 1000},
	{ name = "Glasses 3 Red", texture = "glasses03red", model = "glasses03", id = 15, price = 1000},
	{ name = "Glasses 3 Blue", texture = "glasses03blue", model = "glasses03", id = 15, price = 1000},
	{ name = "Glasses 3 Dark", texture = "glasses03dark", model = "glasses03", id = 15, price = 1000},
	{ name = "Glasses 5 Dark", texture = "glasses05dark", model = "glasses03", id = 15, price = 1000},
	{ name = "Glasses 5", texture = "glasses05", model = "glasses03", id = 15, price = 1000},
	--Watches
},
	["Watches"] = {

	{ name = "Pink Watch", texture = "watchpink", model = "watch", id = 14, price = 1000},
	{ name = "Gold Watch", texture = "watchyellow", model = "watch", id = 14, price = 1000},
	{ name = "Blue Watch", texture = "watchpro", model = "watch", id = 14, price = 1000},
	{ name = "Black Watch", texture = "watchpro2", model = "watch", id = 14, price = 1000},
	{ name = "Round Watch", texture = "watchsub1", model = "watch", id = 14, price = 1000},
	{ name = "Green Watch", texture = "watchsub2", model = "watch", id = 14, price = 1000},
	{ name = "Silver Watch", texture = "watchzip1", model = "watch", id = 14, price = 1000},
	{ name = "Bronze Watch", texture = "watchzip2", model = "watch", id = 14, price = 1000},
	{ name = "Round Gold", texture = "watchgno", model = "watch", id = 14, price = 1000},
	{ name = "Silver Watch", texture = "watchgno2", model = "watch", id = 14, price = 1000},
	{ name = "Gold/Silver Watch", texture = "watchcro", model = "watch", id = 14, price = 1000},
	{ name = "Round Silver", texture = "watchcro2", model = "watch", id = 14, price = 1000},
	
	},--Necklaces
	["Necklaces"]= {
	{ name = "Dogtags", texture = "dogtag", model = "neck", id = 13, price = 1200},
	{ name = "Africa", texture = "neckafrica", model = "neck", id = 13, price = 1200},
	{ name = "Stopwatch", texture = "stopwatch", model = "neck", id = 13, price = 1200},
	{ name = "Saints", texture = "necksaints", model = "neck", id = 13, price = 1200},
	{ name = "Weed", texture = "neckhash", model = "neck", id = 13, price = 1200},
	{ name = "Silver Chain 1", texture = "necksilver", model = "neck2", id = 13, price = 1200},
	{ name = "Gold Chain 1", texture = "neckgold", model = "neck2", id = 13, price = 1200},
	{ name = "Silver Chain 2", texture = "neckropes", model = "neck2", id = 13, price = 1200},
	{ name = "Gold Chain 2", texture = "neckropeg", model = "neck2", id = 13, price = 1200},
	{ name = "LS Necklace", texture = "neckls", model = "neck", id = 13, price = 1200},
	{ name = "Dollar", texture = "neckdollar", model = "neck", id = 13, price = 1200},
	{ name = "Cross", texture = "neckcross", model = "neck", id = 13, price = 1200},
},
}

newClothes = {
	--
	["Hats"] = {
		
	{ name = "Red Bandana", texture = "bandred", model = "bandana", id = 16, price = 150},
	{ name = "Blue Bandana",texture = "bandblue", model = "bandana", id = 16, price = 150},
	{ name = "Green Bandana",texture = "bandgang", model = "bandana", id = 16, price = 150},
	{ name = "Black Bandana",texture = "bandblack", model = "bandana",id =  16, price = 150},
	{ name = "Red Bandana Front",texture = "bandred2", model = "bandknots", id = 16, price = 150},
	{ name = "Blue Bandana Front",texture = "bandblue2", model = "bandknots", id = 16, price = 150},
	{ name = "Green Bandana Front",texture = "bandgang2", model = "bandknots", id = 16, price = 150},
	{ name = "Black Bandana Front",texture = "bandblack2", model = "bandknots", id = 16, price = 150},
	{ name = "Green Knit Cap",texture = "capknitgrn", model = "capknit", id = 16, price = 150},
	{ name = "Trucker Cap",texture = "captruck", model = "captruck", id = 16, price = 150},
	{ name = "Cowboy Hat 1",texture = "cowboy", model = "cowboy", id = 16, price = 150},
	{ name = "Cowboy Hat 2",texture = "hattiger", model = "cowboy", id = 16, price = 150},
	{ name = "Red Motorbike Helmet",texture = "helmet", model = "helmet", id = 16, price = 150},
	{ name = "Blue Motorbike Helmet",texture = "moto", model = "moto", id = 16, price = 150},
	{ name = "Boxing Cap",texture = "boxingcap", model = "boxingcap", id = 16, price = 150},
	{ name = "Hockey Mask",texture = "hockey", model = "hockeymask", id = 16, price = 150},
	{ name = "Green Cap Front",texture = "capgang", model = "cap", id = 16, price = 150},
	{ name = "Green Cap Back",texture = "capgangback", model = "capback", id = 16, price = 150},
	{ name = "Green Cap Side",texture = "capgangside", model = "capside", id = 16, price = 150},
	{ name = "Green Cap Back 2",texture = "capgangover", model = "capovereye", id = 16, price = 150},
	{ name = "Green Cap Up",texture = "capgangup", model = "caprimup", id = 16, price = 150},
	{ name = "Biker Helmet",texture = "bikerhelmet", model = "bikerhelmet", id = 16, price = 150},
	{ name = "Red Cap Front",texture = "capred", model = "cap", id = 16, price = 150},
	{ name = "Red Cap Back",texture = "capredback", model = "capback", id = 16, price = 150},
	{ name = "Red Cap Side",texture = "capredside", model = "capside", id = 16, price = 150},
	{ name = "Red Cap Back 2",texture = "capredover", model = "capovereye", id = 16, price = 150},
	{ name = "Red Cap Up",texture = "capredup", model = "caprimup", id = 16, price = 150},
	{ name = "Blue Cap Front",texture = "capblue", model = "cap", id = 16, price = 150},
	{ name = "Blue Cap Back",texture = "capblueback", model = "capback", id = 16, price = 150},
	{ name = "Blue Cap Side",texture = "capblueside", model = "capside", id = 16, price = 150},
	{ name = "Blue Cap Back 2",texture = "capblueover", model = "capovereye", id = 16, price = 150},
	{ name = "Blue Cap Up",texture = "capblueup", model = "caprimup", id = 16, price = 150},
	{ name = "Black Beanie",texture = "skullyblk", model = "skullycap", id = 16, price = 150},
	{ name = "Green Beanie",texture = "skullygrn", model = "skullycap", id = 16, price = 150},
	{ name = "Black Sunhat",texture = "hatmanblk", model = "hatmanc", id = 16, price = 150},
	{ name = "Striped Sunhat",texture = "hatmancplaid", model = "hatmanc", id = 16, price = 150},
	{ name = "Yellow Cap Front",texture = "capzip", model = "cap", id = 16, price = 150},
	{ name = "Yellow Cap Back",texture = "capzipback", model = "capback", id = 16, price = 150},
	{ name = "Yellow Cap Side",texture = "capzipside", model = "capside", id = 16, price = 150},
	{ name = "Yellow Cap Back 2",texture = "capzipover", model = "capovereye", id = 16, price = 150},
	{ name = "Red Cap Up",texture = "capzipup", model = "caprimup", id = 16, price = 150},
	{ name = "Red Beret",texture = "beretred", model = "beret", id = 16, price = 150},
	{ name = "Black Beret",texture = "beretblk", model = "beret", id = 16, price = 150},
	{ name = "Black Beret",texture = "capblk", model = "cap", id = 16, price = 150},
	{ name = "Black Cap Back",texture = "capblkback", model = "capback", id = 16, price = 150},
	{ name = "Black Cap Side",texture = "capblkside", model = "capside", id = 16, price = 150},
	{ name = "Black Cap Back 2",texture = "capblkover", model = "capovereye", id = 16, price = 150},
	{ name = "Black Cap Up",texture = "capblkup", model = "caprimup", id = 16, price = 150},
	{ name = "Dark Detective  Hat",texture = "trilbydrk", model = "trilby", id = 16, price = 150},
	{ name = "Light Detective Hat",texture = "trilbylght", model = "trilby", id = 16, price = 150},
	{ name = "Black Bowler",texture = "bowler", model = "bowler", id = 16, price = 150},
	{ name = "Red Bowler",texture = "bowlerred", model = "bowler", id = 16, price = 150},
	{ name = "Blue Bowler",texture = "bowlerblue", model = "bowler", id = 16, price = 150},
	{ name = "Yellow Bowler",texture = "bowleryellow", model = "bowler", id = 16, price = 150},
	{ name = "Boater Hat 1",texture = "boater", model = "boater", id = 16, price = 150},
	{ name = "Green Bowler",texture = "bowlergang", model = "bowler", id = 16, price = 150},
	{ name = "Boater Hat 2",texture = "boaterblk", model = "boater", id = 16, price = 150},
	},
	--Shirts
	["Shirts"] = {

	{ name = "No Shirt",texture = "player_torso", model = "torso", id = 0, price = 50},
	{ name = "Black Tanktop",texture = "vestblack", model = "vest", id = 0, price = 250},
	{ name = "White Tanktop",texture = "vest", model = "vest", id = 0, price = 250},
	{ name = "Striped T-Shirt",texture = "tshirt2horiz", model = "tshirt2", id = 0, price = 250},
	{ name = "White T-Shirt",texture = "tshirtwhite", model = "tshirt", id = 0, price = 250},
	{ name = "I <3 LS T-Shirt",texture = "tshirtilovels", model = "tshirt",id = 0, price = 250},
	{ name = "Homies T-Shirt",texture = "tshirtblunts", model = "tshirt", id = 0, price = 250},
	{ name = "Red Checkered Shirt",texture = "shirtbplaid", model = "shirtb", id = 0, price = 250},
	{ name = "Blue Checkered Shirt",texture = "shirtbcheck", model = "shirtb", id = 0, price = 250},
	{ name = "Shirt & T-Shirt Combination",texture = "field", model = "field", id = 0, price = 250},
	{ name = "Green T-Shirt",texture = "tshirterisyell", model = "tshirt", id = 0, price = 250},
	{ name = "Orange T-Shirt",texture = "tshirterisorn", model = "tshirt", id =0, price = 250},
	{ name = "Blue/Red Tracktop",texture = "trackytop2eris", model = "trackytop1", id = 0, price = 250},
	{ name = "Red/White Jacket",texture = "bbjackrim", model = "bbjack", id = 0, price = 250},
	{ name = "Rockstar Jacket",texture = "bballjackrstar", model = "bbjack", id = 0, price = 250},
	{ name = "Basketball Jersey 1",texture = "baskballdrib", model = "baskball", id = 0, price = 250},
	{ name = "Basketball Jersey 2",texture = "baskballrim", model = "baskball", id = 0, price = 250},
	{ name = "69er's Jersey",texture = "sixtyniners", model = "tshirt", id = 0, price = 250},
	{ name = "Bandits Baseball Jersey",texture = "bandits", model = "baseball", id = 0, price = 250},
	{ name = "Red ProLaps T-Shirt",texture = "tshirtprored", model = "tshirt", id = 0, price = 250},
	{ name = "Black ProLaps T-Shirt",texture = "tshirtproblk", model = "tshirt", id = 0, price = 250},
	{ name = "ProLaps Tracktop",texture = "trackytop1pro", model = "trackytop1", id = 0, price = 250},
	{ name = "Hockey Jersey",texture = "hockeytop", model = "sweat", id = 0, price = 250},
	{ name = "ProLaps White Sleeve",texture = "bbjersey", model = "sleevt", id = 0, price = 250},
	{ name = "Shellsuit Tracktop",texture = "shellsuit", model = "trackytop1", id = 0, price = 250},
	{ name = "White TruReligion Shirt",texture = "tshirtheatwht", model = "tshirt", id = 0, price = 250},
	{ name = "Bobo Monkey T-Shirt", texture = "tshirtbobomonk", model = "tshirt", id = 0, price = 250},
	{ name = "#80 Red T-Shirt", texture = "tshirtbobored", model = "tshirt", id = 0, price = 250},
	{ name = "Base-5 T-Shirt", texture = "tshirtbase5", model = "tshirt", id = 0, price = 250},
	{ name = "SubUrban T-Shirt", texture = "tshirtsuburb", model = "tshirt", id = 0, price = 250},
	{ name = "QuickSilver Hoodie", texture = "hoodyamerc", model = "hoodya", id = 0, price = 250},
	{ name = "Base-5 Hoody", texture = "hoodyabase5", model = "hoodya", id = 0, price = 250},
	{ name = "Rockstar Hoody", texture = "hoodyarockstar", model = "hoodya", id = 0, price = 250},
	{ name = "White/Blue T-Shirt Coat", texture = "wcoatblue", model = "wcoat", id = 0, price = 250},
	{ name = "Military Green Shirt", texture = "coach", model = "coach", id = 0, price = 250},
	{ name = "Semi Military Green Shirt", texture = "semicoach", model = "coach", id = 0, price = 250},
	{ name = "Rockstar Sweater", texture = "sweatrstar", model = "sweat", id = 0, price = 250},
	{ name = "Blue Rockstar Hoody", texture = "hoodyAblue", model = "hoodyA", id = 0, price = 250},
	{ name = "Black Rockstar Hoody", texture = "hoodyAblack", model = "hoodyA", id = 0, price = 250},
	{ name = "Green Rockstar Hoody", texture = "hoodyAgreen", model = "hoodyA", id = 0, price = 250},
	{ name = "Brown Sleeve Shirt", texture = "sleevtbrown", model = "sleevt", id = 0, price = 250},
	{ name = "Light Blue Shirt", texture = "shirtablue", model = "shirta", id = 0, price = 250},
	{ name = "Light Yellow Shirt", texture = "shirtayellow", model = "shirta", id = 0, price = 250},
	{ name = "Grey Shirt", texture = "shirtagrey", model = "shirta", id = 0, price = 250},
	{ name = "Green Shirt", texture = "shirtbgang", model = "shirtb", id = 0, price = 250},
	{ name = "Cream ZIP T-Shirt", texture = "tshirtzipcrm", model = "tshirt", id = 0, price = 250},
	{ name = "Grey ZIP T-Shirt", texture = "tshirtzipgry", model = "tshirt", id = 0, price = 250},
	{ name = "Faded Demin Jacket", texture = "denimfade", model = "denimfade", id = 0, price = 250},
	{ name = "Bowling T-Shirt", texture = "bowling", model = "hawaii", id = 0, price = 250},
	{ name = "Beige Hoody Jacket", texture = "hoodjackbeige", model = "hoodjack", id = 0, price = 250},
	{ name = "Gold Basketball Jersey", texture = "baskballloc", model = "backball", id = 0, price = 250},
	{ name = "Handcuff's T-Shirt", texture = "tshirtlocgrey", model = "tshirt", id = 0, price = 250},
	{ name = "Grey Uzi T-Shirt", texture = "tshirtmaddgrey", model = "tshirt", id = 0, price = 250},
	{ name = "Green Uzi T-Shirt", texture = "tshirtmaddgrn", model = "tshirt", id = 0, price = 250},
	{ name = "Grey Suit Jacket", texture = "suit1grey", model = "suit1", id = 0, price = 250},
	{ name = "Black Suit Jacket", texture = "suit1blk", model = "suit1", id = 0, price = 250},
	{ name = "Leather Jacket", texture = "leather", model = "leather", id = 0, price = 250},
	{ name = "Painter Jacket", texture = "painter", model = "painter", id = 0, price = 250},
	{ name = "White Hawaii Shirt", texture = "hawaiiwht", model = "hawaii", id = 0, price = 250},
	{ name = "White Hawaii Shirt 2", texture = "hawaiired", model = "hawaii", id = 0, price = 250},
	{ name = "Sport's Tracktop", texture = "sportjack", model = "trackytop1", id = 0, price = 250},
	{ name = "Red Suit Jacket", texture = "suit1red", model = "suit1", id = 0, price = 250},
	{ name = "Blue Suit Jacket", texture = "suit1blue", model = "suit1", id = 0, price = 250},
	{ name = "Yellow Suit Jacket", texture = "suit1yellow", model = "suit1", id = 0, price = 250},
	{ name = "Green Tuxedo Jacket", texture = "suit2green", model = "suit2", id = 0, price = 250},
	{ name = "Black Tuxedo Jacket", texture = "tuxedo", model = "suit2", id = 0, price = 250},
	{ name = "Green Suit Jacket", texture = "suit1gang", model = "suit1", id = 0, price = 250},
	{ name = "Blue R Sleeve", texture = "letter", model = "sleevt", id = 0, price = 250},
	},
	--Trousers
	["Pants"] = {

	{ name = "No Trousers",texture = "player_legs", model = "legs", id = 2, price = 50},
	{ name = "Black Boxer Briefs",texture = "legsblack", model = "legs", id = 2, price = 750},
	{ name = "Hearted Boxer Briefs",texture = "legsheart", model = "legs", id = 2, price = 750},
	{ name = "Camo Green Trousers",texture = "worktrcamogrn", model = "worktr", id = 2, price = 750},
	{ name = "Camo Grey Trousers",texture = "worktrcamogry", model = "worktr", id = 2, price = 750},
	{ name = "Grey Cargopants",texture = "worktrgrey", model = "worktr", id = 2, price = 750},
	{ name = "Khaki Cargopants",texture = "worktrkhaki", model = "worktr", id = 2, price = 750},
	{ name = "White Trackpants",texture = "tracktr", model = "tracktr", id = 2, price = 750},
	{ name = "Navy Blue Trackpants",texture = "tracktreris", model = "tracktr", id = 2, price = 750},
	{ name = "Denim Jeans",texture = "jeansdenim", model = "jeans", id = 2, price = 750},
	{ name = "Biege Khakis",texture = "biegetr", model = "chinosb", id = 2, price = 750},
	{ name = "Red Trackpants",texture = "tracktrpro", model = "tracktr", id = 2, price = 750},
	{ name = "Grey Trackpants",texture = "tracktrwhstr", model = "tracktr", id = 2, price = 750},
	{ name = "Blue Trackpants",texture = "tracktrblue", model = "tracktr", id = 2, price = 750},
	{ name = "Green Trackpants",texture = "tracktrgang", model = "tracktr", id = 2, price = 750},
	{ name = "White Boxing Shorts",texture = "bbshortwht", model = "boxingshort",id =  2, price = 750},
	{ name = "Blood Red Boxing Shorts",texture = "bbshort", model = "boxingshort", id = 2, price = 750},
	{ name = "Regular Red Boxing Shorts",texture = "bbshortred", model = "boxingshort", id = 2, price = 750},
	{ name = "Muli-Color Trackpants",texture = "shellsuittr", model = "tracktr", id = 2, price = 750},
	{ name = "Grey Cargoshorts",texture = "shortsgrey", model = "shorts", id = 2, price = 750},
	{ name = "Khaki Cargoshorts",texture = "shortskhaki", model = "shorts", id = 2, price = 750},
	{ name = "Green Shorts 1",texture = "chongergang", model = "chonger", id = 2, price = 750},
	{ name = "Red Shorts",texture = "chongerred", model = "chonger", id = 2, price = 750},
	{ name = "Blue Shorts",texture = "chongerblue", model = "chonger", id = 2, price = 750},
	{ name = "Green Shorts 2",texture = "shortsgang", model = "shorts", id = 2, price = 750},
	{ name = "Denim Green Jeans",texture = "denimgang", model = "jeans", id = 2, price = 750},
	{ name = "Denim Red Jeans",texture = "denimred", model = "jeans", id = 2, price = 750},
	{ name = "Biege Chinos",texture = "chinosbiege", model = "chinosb", id = 2, price = 750},
	{ name = "Khaki Chinos",texture = "chinoskhaki", model = "chinosb", id = 2, price = 750},
	{ name = "Chino Shorts",texture = "cutoffchinos", model = "shorts", id = 2, price = 750},
	{ name = "Blue Chino Shorts",texture = "cutoffchinosblue", model = "shorts", id = 2, price = 750},
	{ name = "Black Chinos",texture = "chinosblack", model = "chinosb", id = 2, price = 750},
	{ name = "Blue Chinos",texture = "chinosblue", model = "chinosb", id = 2, price = 750},
	{ name = "Leather Jeans 1",texture = "leathertr", model = "leathertr", id = 2, price = 750},
	{ name = "Leather Jeans 2",texture = "leathertrchaps", model = "leathertr", id = 2, price = 750},
	{ name = "Grey Suit Pants",texture = "suit1trgrey", model = "suit1tr", id = 2, price = 750},
	{ name = "Black Suit Pants",texture = "suit1trblk", model = "suit1tr", id = 2, price = 750},
	{ name = "Demin Cut-Off Shorts",texture = "cutoffdemins", model = "shorts", id = 2, price = 750},
	{ name = "Red Suit Pants",texture = "suit1trred", model = "suit1tr", id = 2, price = 750},
	{ name = "Blue Suit Pants",texture = "suit1trblue", model = "suit1tr", id = 2, price = 750},
	{ name = "Gold Suit Pants",texture = "suit1tryellow", model = "suit1tr", id = 2, price = 750},
	{ name = "Green Tuxedo Pants",texture = "suit1trgreen", model = "suit1tr", id = 2, price = 750},
	{ name = "Black Tuxedo Pants",texture = "suit1trblk2", model = "suit1tr", id = 2, price = 750},
	{ name = "Green Suit Pants",texture = "suit1trgang", model = "suit1tr", id = 2, price = 750},
},
	--Shoes

["Shoes"] = {
	{ name = "No Shoes", texture = "foot", model = "feet", id = 3, price = 1050},
	{ name = "Cowboy Boots", texture = "cowboyboot2", model = "biker", id = 3, price = 1050},
	{ name = "White & Grey BasketBall Shoes", texture = "bask2semi", model = "bask1", id = 3, price = 1050},
	{ name = "White Basketball Shoes", texture = "bask1eris", model = "bask1", id = 3, price = 1050},
	{ name = "Green Sneakers", texture = "sneakerbincgang", model = "sneaker", id = 3, price = 1050},
	{ name = "Blue Sneakers", texture = "sneakerbincblue", model = "sneaker", id = 3, price = 1050},
	{ name = "Black Sneakers", texture = "sneakerbincblk", model = "sneaker", id = 3, price = 1050},
	{ name = "Black Sandals", texture = "sandal", model = "flipflop", id = 3, price = 1050},
	{ name = "Black Sandals w/th Socks", texture = "sandalsock", model = "flipflop", id = 3, price = 1050},
	{ name = "Black & Blue Flip-Flops", texture = "flipflop", model = "flipflop", id = 3, price = 1050},
	{ name = "White & Blue Hi-Tops", texture = "hitop", model = "bask1", id = 3, price = 1050},
	{ name = "Black Converse Shoes 1", texture = "convproblk", model = "conv", id = 3, price = 1050},
	{ name = "Blue Converse Shoes", texture = "convproblu", model = "conv", id = 3, price = 1050},
	{ name = "Green Converse Shoes", texture = "convprogrn", model = "conv", id = 3, price = 1050},
	{ name = "Red Sneakers", texture = "sneakerprored", model = "sneaker", id = 3, price = 1050},
	{ name = "Blue Sneakers", texture = "sneakerproblu", model = "sneaker", id = 3, price = 1050},
	{ name = "White Sneakers 1", texture = "sneakerprowht", model = "sneaker", id = 3, price = 1050},
	{ name = "White & Red Basketball Shoes", texture = "bask1prowht", model = "bask1", id = 3, price = 1050},
	{ name = "Black Basketball Shoes", texture = "bask1problk", model = "bask1", id = 3, price = 1050},
	{ name = "Boxing Shoes", texture = "boxingshoe", model = "biker", id = 3, price = 1050},
	{ name = "Black Converse Shoes 2", texture = "convheatblk", model = "conv", id = 3, price = 1050},
	{ name = "Red Converse Shoes", texture = "convheatred", model = "conv", id = 3, price = 1050},
	{ name = "Orange Converse Shoes", texture = "convheatorn", model = "conv", id = 3, price = 1050},
	{ name = "White Sneakers", texture = "sneakerheatwht", model = "sneaker", id = 3, price = 1050},
	{ name = "Grey Sneakers", texture = "sneakerheatgry", model = "sneaker", id = 3, price = 1050},
	{ name = "Black & Grey Sneakers", texture = "sneakerheatblk", model = "sneaker", id = 3, price = 1050},
	{ name = "White Sneakers 2", texture = "bask2heatwht", model = "bask1", id = 3, price = 1050},
	{ name = "Blue & White Basketball Shoes", texture = "bask2heatband", model = "bask1", id = 3, price = 1050},
	{ name = "Grey Basketball Shoes", texture = "timbergrey", model = "bask1", id = 3, price = 1050},
	{ name = "Red Basketball Shoes", texture = "timberred", model = "bask1", id = 3, price = 1050},
	{ name = "Brown Hiking Shoes", texture = "timberfawn", model = "bask1", id = 3, price = 1050},
	{ name = "Green Hiking Shoes", texture = "timberhike", model = "bask1", id = 3, price = 1050},
	{ name = "Black & White Cowboy Boots", texture = "cowboyboot", model = "biker", id = 3, price = 1050},
	{ name = "Biker Boots", texture = "biker", model = "biker", id = 3, price = 1050},
	{ name = "Snake Boots", texture = "snakeskin", model = "biker", id = 3, price = 1050},
	{ name = "Black Dress Shoes", texture = "shoedressblk", model = "shoe", id = 3, price = 1050},
	{ name = "Brown Dress Shoes", texture = "shoedressbrn", model = "shoe", id = 3, price = 1050},
	{ name = "Black & White Shoes", texture = "shoespaz", model = "shoe", id = 3, price = 1050},
	},
	--Hair
	["Hair"] = {
	{ name = "Regular Hair", texture = "player_face", model = "head", id = 1, price = 150},
	{ name = "Blond Hair", texture = "hairblond", model = "head", id = 1, price = 150},
	{ name = "Red Hair", texture = "hairred", model = "head", id = 1, price = 150},
	{ name = "Blue Hair", texture = "hairblue", model = "head", id = 1, price = 150},
	{ name = "Green Hair", texture = "hairgreen", model = "head", id = 1, price = 150},
	{ name = "Pink Hair", texture = "hairpink", model = "head", id = 1, price = 150},
	{ name = "Bald", texture = "bald", model = "head", id = 1, price = 150},
	{ name = "Bald w/th Beard", texture = "baldbeard", model = "head", id = 1, price = 150},
	{ name = "Bald w/th Stash", texture = "baldtash", model = "head", id = 1, price = 150},
	{ name = "Bald w/th Goatee", texture = "baldgoatee", model = "head", id = 1, price = 150},
	{ name = "High Fade", texture = "highfade", model = "head", id = 1, price = 150},
	{ name = "High Afro", texture = "highafro", model = "highafro", id = 1, price = 150},
	{ name = "Wedge", texture = "wedge", model = "wedge", id = 1, price = 150},
	{ name = "Slope", texture = "slope", model = "slope", id = 1, price = 150},
	{ name = "Curls", texture = "jhericurl", model = "jheri", id = 1, price = 150},
	{ name = "Cornrows", texture = "cornrows", model = "cornrows", id = 1, price = 150},
	{ name = "Blondrows", texture = "cornrowsb", model = "cornrows", id = 1, price = 150},
	{ name = "Tramline", texture = "tramline", model = "tramline", id = 1, price = 150},
	{ name = "Groove Cut", texture = "groovecut", model = "groovecut", id = 1, price = 150},
	{ name = "Mohawk", texture = "mohawk", model = "mohawk", id = 1, price = 150},
	{ name = "Blond Mohawk", texture = "mohawkblond", model = "mohawk", id = 1, price = 150},
	{ name = "Pink Mohawk", texture = "mohawkpink", model = "mohawk", id = 1, price = 150},
	{ name = "Mohawk w/th Beard", texture = "mohawkbeard", model = "mohawk", id = 1, price = 150},
	{ name = "Afro", texture = "afro", model = "afro", id = 1, price = 150},
	{ name = "Afro w/th Stash", texture = "afrotash", model = "afro", id = 1, price = 150},
	{ name = "Afro w/th Goatee", texture = "afrobeard", model = "afro", id = 1, price = 150},
	{ name = "Blond Afro", texture = "afroblond", model = "afro", id = 1, price = 150},
	{ name = "Flat Top", texture = "flattop", model = "flattop", id = 1, price = 150},
	{ name = "Elvis Hair", texture = "elvishair", model = "elvishair", id = 1, price = 150},
	{ name = "Regular w/th Beard", texture = "beard", model = "head", id = 1, price = 150},
	{ name = "Regular w/th Stash", texture = "tash", model = "head", id = 1, price = 150},
	{ name = "Regular w/th Goatee", texture = "goatee", model = "head", id = 1, price = 150},
	{ name = "Afro w/th Goatee", texture = "afrogoatee", model = "afro", id = 1, price = 150},
	
	},--[[Extras
	["Extras"] = {
	{ name = "Gimpsuit", texture = "gimpleg", model = "gimpleg", id = 17, price = 2500},
	{ name = "Valet", texture = "valet", model = "valet", id = 17, price = 2500},
	{ name = "Croupier", texture = "croupier", model = "valet", id = 17, price = 2500},
	{ name = "Country", texture = "countrytr", model = "countrytr", id = 17, price = 2500},
	{ name = "Police", texture = "policetr", model = "policetr", id = 17, price = 2500},
	{ name = "Balaclava", texture = "balaclava", model = "balaclava", id = 17, price = 2500},
	{ name = "Pimpsuit", texture = "pimptr", model = "pimptr", id = 17, price = 2500},
	{ name = "Mech/Racer", texture = "garageleg", model = "garagetr", id = 17, price = 2500},
	{ name = "Medic", texture = "medictr", model = "medictr", id = 17, price = 2500},
	
	},--]]--Glasses
	["Glasses"] = 
	{
	{ name = "Fake Nose", texture = "groucho", model = "groucho", id = 15, price = 1000},
	{ name = "Zorro", texture = "zorro", model = "zorromask", id = 15, price = 1000},
	{ name = "Eyepatch", texture = "eyepatch", model = "eyepatch", id = 15, price = 1000},
	{ name = "Glasses 1", texture = "glasses01", model = "glasses01", id = 15, price = 1000},
	{ name = "Glasses 4", texture = "glasses01", model = "glasses04", id = 15, price = 1000},
	{ name = "Red Band Mask", texture = "bandred3", model = "bandmask", id = 15, price = 1000},
	{ name = "Blue Band Mask", texture = "bandblue3", model = "bandmask", id = 15, price = 1000},
	{ name = "Green Band Mask", texture = "bandgang3", model = "bandmask", id = 15, price = 1000},
	{ name = "Black Band Mask", texture = "bandblack3", model = "bandmask", id = 15, price = 1000},
	{ name = "Glasses 1 Dark", texture = "glasses01dark", model = "glasses01", id = 15, price = 1000},
	{ name = "Glasses 4 Dark", texture = "glasses04dark", model = "glasses04", id = 15, price = 1000},
	{ name = "Glasses 3", texture = "glasses03", model = "glasses03", id = 15, price = 1000},
	{ name = "Glasses 3 Red", texture = "glasses03red", model = "glasses03", id = 15, price = 1000},
	{ name = "Glasses 3 Blue", texture = "glasses03blue", model = "glasses03", id = 15, price = 1000},
	{ name = "Glasses 3 Dark", texture = "glasses03dark", model = "glasses03", id = 15, price = 1000},
	{ name = "Glasses 5 Dark", texture = "glasses05dark", model = "glasses03", id = 15, price = 1000},
	{ name = "Glasses 5", texture = "glasses05", model = "glasses03", id = 15, price = 1000},
	--Watches
},
	["Watches"] = {

	{ name = "Pink Watch", texture = "watchpink", model = "watch", id = 14, price = 1000},
	{ name = "Gold Watch", texture = "watchyellow", model = "watch", id = 14, price = 1000},
	{ name = "Blue Watch", texture = "watchpro", model = "watch", id = 14, price = 1000},
	{ name = "Black Watch", texture = "watchpro2", model = "watch", id = 14, price = 1000},
	{ name = "Round Watch", texture = "watchsub1", model = "watch", id = 14, price = 1000},
	{ name = "Green Watch", texture = "watchsub2", model = "watch", id = 14, price = 1000},
	{ name = "Silver Watch", texture = "watchzip1", model = "watch", id = 14, price = 1000},
	{ name = "Bronze Watch", texture = "watchzip2", model = "watch", id = 14, price = 1000},
	{ name = "Round Gold", texture = "watchgno", model = "watch", id = 14, price = 1000},
	{ name = "Silver Watch", texture = "watchgno2", model = "watch", id = 14, price = 1000},
	{ name = "Gold/Silver Watch", texture = "watchcro", model = "watch", id = 14, price = 1000},
	{ name = "Round Silver", texture = "watchcro2", model = "watch", id = 14, price = 1000},
	
	},--Necklaces
	["Necklaces"]= {
	{ name = "Dogtags", texture = "dogtag", model = "neck", id = 13, price = 1200},
	{ name = "Africa", texture = "neckafrica", model = "neck", id = 13, price = 1200},
	{ name = "Stopwatch", texture = "stopwatch", model = "neck", id = 13, price = 1200},
	{ name = "Saints", texture = "necksaints", model = "neck", id = 13, price = 1200},
	{ name = "Weed", texture = "neckhash", model = "neck", id = 13, price = 1200},
	{ name = "Silver Chain 1", texture = "necksilver", model = "neck2", id = 13, price = 1200},
	{ name = "Gold Chain 1", texture = "neckgold", model = "neck2", id = 13, price = 1200},
	{ name = "Silver Chain 2", texture = "neckropes", model = "neck2", id = 13, price = 1200},
	{ name = "Gold Chain 2", texture = "neckropeg", model = "neck2", id = 13, price = 1200},
	{ name = "LS Necklace", texture = "neckls", model = "neck", id = 13, price = 1200},
	{ name = "Dollar", texture = "neckdollar", model = "neck", id = 13, price = 1200},
	{ name = "Cross", texture = "neckcross", model = "neck", id = 13, price = 1200},
},
}

types = {
	{ name = "Hair", id = 1},
	{ name = "Pants", id = 2},
	{ name = "Shoes", id = 3},
	{ name = "Hats", id = 16},
	{ name = "Shirts", id = 0},
	{ name = "Glasses", id = 15},
	{ name = "Watches", id = 14},
	{ name = "Necklaces", id = 13},
	--{ name = "Extras", id = 17},
}